version: 2
updates:
  - package-ecosystem: bun
    directory: /web
    schedule:
      interval: monthly
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
  - package-ecosystem: bun
    directory: /firebase
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
