package io.hafa.latr.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// latr's own palette, used only where the phone offers no dynamic colors (previews, tests).
// Roles carry meaning: primary = done, tertiary = snooze, error = delete.
val LatrLightColors = lightColorScheme(
    primary = Color(0xFF1F7A5C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE6F3ED),
    onPrimaryContainer = Color(0xFF0E3D2D),
    secondary = Color(0xFF2F6FDE),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEAF1FD),
    onSecondaryContainer = Color(0xFF1F4FA8),
    tertiary = Color(0xFFA86200),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFBF1E1),
    onTertiaryContainer = Color(0xFF5C3600),
    error = Color(0xFFD23F3A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFCEBEA),
    onErrorContainer = Color(0xFF7A1D1A),
    background = Color(0xFFFBFAF8),
    onBackground = Color(0xFF2B2A27),
    surface = Color(0xFFFBFAF8),
    onSurface = Color(0xFF2B2A27),
    surfaceVariant = Color(0xFFF4F3F0),
    onSurfaceVariant = Color(0xFF6B6963),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFFFFF),
    surfaceContainer = Color(0xFFF4F3F0),
    surfaceContainerHigh = Color(0xFFEEEDE9),
    surfaceContainerHighest = Color(0xFFE8E6E2),
    outline = Color(0xFF9A9892),
    outlineVariant = Color(0xFFE8E6E2),
    inverseSurface = Color(0xFF2B2A27),
    inverseOnSurface = Color(0xFFF4F3F0),
    inversePrimary = Color(0xFF9EC0FA),
)

val LatrDarkColors = darkColorScheme(
    primary = Color(0xFF5CC29A),
    onPrimary = Color(0xFF0B2A1F),
    primaryContainer = Color(0xFF15302A),
    onPrimaryContainer = Color(0xFFB9E8D4),
    secondary = Color(0xFF74A4F5),
    onSecondary = Color(0xFF0F1B2E),
    secondaryContainer = Color(0xFF1C2A40),
    onSecondaryContainer = Color(0xFFC7DAFB),
    tertiary = Color(0xFFE0A44A),
    onTertiary = Color(0xFF2E1D00),
    tertiaryContainer = Color(0xFF33270F),
    onTertiaryContainer = Color(0xFFF5D7A8),
    error = Color(0xFFF07A72),
    onError = Color(0xFF3A0B08),
    errorContainer = Color(0xFF3A1C1A),
    onErrorContainer = Color(0xFFF8C4BF),
    background = Color(0xFF171615),
    onBackground = Color(0xFFECEBE8),
    surface = Color(0xFF171615),
    onSurface = Color(0xFFECEBE8),
    surfaceVariant = Color(0xFF1E1D1B),
    onSurfaceVariant = Color(0xFFA9A7A1),
    surfaceContainerLowest = Color(0xFF121110),
    surfaceContainerLow = Color(0xFF1E1D1B),
    surfaceContainer = Color(0xFF1B1A19),
    surfaceContainerHigh = Color(0xFF252422),
    surfaceContainerHighest = Color(0xFF2E2C2A),
    outline = Color(0xFF75736E),
    outlineVariant = Color(0xFF2E2C2A),
    inverseSurface = Color(0xFFECEBE8),
    inverseOnSurface = Color(0xFF1E1D1B),
    inversePrimary = Color(0xFF2F6FDE),
)
